### ISSUE TITLE
AVX data set

### ISSUE THREAD

**Issue by SilentJCR** [aydnzn/Enhancing-LiDAR-based-3D-Object-Detection#1]
Hi, I found this place and spent some time reading the paper and readme.md. 
A lot of experiments regarding combining KITTI and AVX dataset with different proportions have been done.

I have a few questions that I would like to see them clarified.

1. Does the AVX dataset contain reflectance(intensity) values for each point cloud? There's some synthetic data that contains x,y,z info of the point clouds but their intensity values are set to 0.
2. I know that KITTI dataset is open to public. I'm wondering if AVX dataset is provided.

Thanks.

**Comment by aydnzn** [comment]
Hello,

Thank you for your interest in my master's thesis.

1. **Appendix A.3 Reference**: Please refer to appendix A.3 (pages 132 and 133) of my thesis. The text file provided there represents a subset of the point cloud output generated by AVX, capturing the first 30 points within the point cloud. A detailed exploration of its structure is available in section 3.3.1 (pages 53, 54). The output begins with a line confirming that the LiDAR is of the rotating type, followed by lines in the format: `float Xx float Yx float Zx float Ix Int Rx`. Here, `Xx`, `Yx`, `Zx` represent the coordinates of the return for beam x in three-dimensional space. `Ix` indicates the normalized amplitude of the current for beam x, ranging from 0 to 1, where 1 represents maximum current. `Rx` denotes the return number for beam x, which is consistently 1 for all points due to the settings in section 3.1.1.5.

   However, there's a caveat. As detailed in 3.3.1, a ‘1’ for the intensity value corresponds to maximum current, which is elaborated on page 41. A high model value of 100,000mA is used, which is significantly large, thus making the intensity values in the Appendix somewhat misleading as they are lower compared to real-world scenarios. The exact value of maximum current for the photodiode would have provided more accurate intensity values.

   **Regarding the maximum current**: The saturation current of a photodiode is its upper output current limit. Operating at or above this limit can distort the signal and decrease measurement accuracy. In the model, a high value of 100,000mA is used to avoid potential saturation, as the exact saturation current value isn't provided in A.1.

2. **AVX Dataset Availability**: As far as I am aware, the AVX dataset is not openly available to the public. However, you might want to contact my supervisor, Petr at Ansys, for more specific information: [petr.fomin@ansys.com](mailto:petr.fomin@ansys.com).

Hope this clarifies your queries. Feel free to reach out if you have more questions or need further assistance.

Best regards,
Aydin
